<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'sku' => 'GOLD-24K-001',
                'type_id' => 1,
                'name' => 'Pure Gold Bar 24K',
                'price' => 124664.30,
                'image' => '',

                'purity_id' => 1,
                'unit_id' => 2,
                'gross_weight' => 10.0000,
                'net_weight' => 10.0000,
                'making_charge' => 0.00,
                'rate_per_gram' => 12343.00,
                'gst_percent' => 1.00,
                'stock_qty' => 1.0000,
                'pstatus' => 'in_stock',
                'status' => 0,
                'created_at' => '2025-11-28 05:37:38',
                'updated_at' => '2025-11-28 00:34:50',
            ],
            [
                'id' => 2,
                'sku' => 'GOLD-22K-002',
                'type_id' => 5,
                'name' => 'Gold Bangle 22K',
                'price' => 96895.36,
                'image' => '',

                'purity_id' => 2,
                'unit_id' => 2,
                'gross_weight' => 8.0000,
                'net_weight' => 8.0000,
                'making_charge' => 0.00,
                'rate_per_gram' => 11992.00,
                'gst_percent' => 1.00,
                'stock_qty' => 1.0000,
                'pstatus' => 'in_stock',
                'status' => 0,
                'created_at' => '2025-11-28 05:38:38',
                'updated_at' => '2025-11-28 00:36:32',
            ],
            [
                'id' => 3,
                'sku' => 'GOLD-18K-003',
                'type_id' => 2,
                'name' => 'Gold Ring 18K',
                'price' => 56097.42,
                'image' => '',

                'purity_id' => 3,
                'unit_id' => 2,
                'gross_weight' => 6.0000,
                'net_weight' => 6.0000,
                'making_charge' => 0.00,
                'rate_per_gram' => 9257.00,
                'gst_percent' => 1.00,
                'stock_qty' => 1.0000,
                'pstatus' => 'in_stock',
                'status' => 0,
                'created_at' => '2025-11-28 05:39:36',
                'updated_at' => '2025-11-28 00:36:48',
            ],
            [
                'id' => 4,
                'sku' => 'GOLD-14K-004',
                'type_id' => 4,
                'name' => 'Gold Necklace 14K',
                'price' => 87264.00,
                'image' => '',

                'purity_id' => 4,
                'unit_id' => 2,
                'gross_weight' => 12.0000,
                'net_weight' => 12.0000,
                'making_charge' => 0.00,
                'rate_per_gram' => 7200.00,
                'gst_percent' => 1.00,
                'stock_qty' => 1.0000,
                'pstatus' => 'in_stock',
                'status' => 0,
                'created_at' => '2025-11-28 05:40:42',
                'updated_at' => '2025-11-28 00:37:00',
            ],
            [
                'id' => 5,
                'sku' => 'GOLD-9K-005',
                'type_id' => 5,
                'name' => 'Gold Bracelet 9K',
                'price' => 23376.45,
                'image' => '',

                'purity_id' => 5,
                'unit_id' => 2,
                'gross_weight' => 5.0000,
                'net_weight' => 5.0000,
                'making_charge' => 0.00,
                'rate_per_gram' => 4629.00,
                'gst_percent' => 1.00,
                'stock_qty' => 1.0000,
                'pstatus' => 'in_stock',
                'status' => 0,
                'created_at' => '2025-11-28 05:41:48',
                'updated_at' => '2025-11-28 00:37:11',
            ],
            [
                'id' => 6,
                'sku' => 'SILVER-925-006',
                'type_id' => 19,
                'name' => 'Silver Pendant 925',
                'price' => 2620.95,
                'image' => '',

                'purity_id' => 8,
                'unit_id' => 2,
                'gross_weight' => 15.0000,
                'net_weight' => 15.0000,
                'making_charge' => 0.00,
                'rate_per_gram' => 173.00,
                'gst_percent' => 1.00,
                'stock_qty' => 1.0000,
                'pstatus' => 'in_stock',
                'status' => 0,
                'created_at' => '2025-11-28 05:43:05',
                'updated_at' => '2025-11-28 00:37:24',
            ],
            [
                'id' => 7,
                'sku' => 'SILVER-958-007',
                'type_id' => 22,
                'name' => 'Silver Coin 958',
                'price' => 3494.60,
                'image' => '',

                'purity_id' => 7,
                'unit_id' => 2,
                'gross_weight' => 20.0000,
                'net_weight' => 20.0000,
                'making_charge' => 0.00,
                'rate_per_gram' => 173.00,
                'gst_percent' => 1.00,
                'stock_qty' => 1.0000,
                'pstatus' => 'in_stock',
                'status' => 0,
                'created_at' => '2025-11-28 05:44:10',
                'updated_at' => '2025-11-28 00:37:35',
            ],
            [
                'id' => 8,
                'sku' => 'SILVER-999-008',
                'type_id' => 12,
                'name' => 'Silver Bar 999',
                'price' => 4418.75,
                'image' => '',

                'purity_id' => 6,
                'unit_id' => 12,
                'gross_weight' => 25.0000,
                'net_weight' => 25.0000,
                'making_charge' => 50.00,
                'rate_per_gram' => 173.00,
                'gst_percent' => 1.00,
                'stock_qty' => 1.0000,
                'pstatus' => 'in_stock',
                'status' => 0,
                'created_at' => '2025-11-28 05:45:20',
                'updated_at' => '2025-11-28 00:37:48',
            ],
            [
                'id' => 9,

                'sku' => 'SILVER-925-009',
                'type_id' => 18,
                'name' => 'Silver Earring 925',
                'price' => 554.49,
                'image' => '',

                'purity_id' => 8,
                'unit_id' => 2,
                'gross_weight' => 3.0000,
                'net_weight' => 3.0000,
                'making_charge' => 30.00,
                'rate_per_gram' => 173.00,
                'gst_percent' => 1.00,
                'stock_qty' => 1.0000,
                'pstatus' => 'in_stock',
                'status' => 0,
                'created_at' => '2025-11-28 05:46:38',
                'updated_at' => '2025-11-28 00:37:59',
            ],
            [
                'id' => 10,

                'sku' => 'SILVER-958-010',
                'type_id' => 13,
                'name' => 'Silver Ring 958',
                'price' => 739.32,
                'image' => '',

                'purity_id' => 7,
                'unit_id' => 2,
                'gross_weight' => 4.0000,
                'net_weight' => 4.0000,
                'making_charge' => 40.00,
                'rate_per_gram' => 173.00,
                'gst_percent' => 1.00,
                'stock_qty' => 1.0000,
                'pstatus' => 'in_stock',
                'status' => 0,
                'created_at' => '2025-11-28 05:48:00',
                'updated_at' => '2025-11-28 01:09:06',
            ],
        ]);
    }
}
